[Unit]
Description={{app_description}}
After=network.target

[Service]
WorkingDirectory={{deploy_path}}
ExecStart={{dotnet_exec}} {{deploy_path}}/{{assembly_name}}.dll
Restart=always
RestartSec=10
KillSignal=SIGINT
User={{deploy_user}}
{{environment_vars}}
EnvironmentFile=-{{env_file}}
SyslogIdentifier={{service_name}}
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
